apiVersion: v1
kind: Namespace
metadata:
  name: weather-api
---
apiVersion: v1
kind: Secret
metadata:
  name: owm-credentials
  namespace: weather-api
stringData:
  key: ${APP_OWM_API_KEY}
---
apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
  namespace: weather-api
  labels:
    app: weather-api
spec:
  type: LoadBalancer
  selector:
    app: weather-api
  ports:
    - name: http
      targetPort: 8000
      port: 8000
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-api-config
  namespace: weather-api
data:
  cacheTtl: "300"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-api
  name: weather-api
  namespace: weather-api
spec:
  selector:
    matchLabels:
      app: weather-api
  replicas: 3
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - image: local.dev/weather-api:latest
          name: weather-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: APP_OWM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: owm-credentials
                  key: key
            - name: APP_CACHE_TTL
              valueFrom:
                configMapKeyRef:
                  name: weather-api-config
                  key: cacheTtl
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
